### ISSUE TITLE
Not working in Blender 3.3.0

### ISSUE THREAD

**Issue by zynzeki** [banan039pl/Models-Resource-Blender-Importer#1]
After setting the folder path for the cache, the addon doesn't load, and I get this error:

`Exception in thread Thread-2 (get_platforms_thread):
Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\skull\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Models_Resource_Importer\Models_Resource_Soup.py", line 117, in get_platforms_thread
    data = get_platforms(wm.url)
  File "C:\Users\skull\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Models_Resource_Importer\Models_Resource_Soup.py", line 90, in get_platforms
    return get_list(url,  "div", {"id": 'leftnav-consoles'})
  File "C:\Users\skull\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Models_Resource_Importer\Models_Resource_Soup.py", line 71, in get_list
    soup = BS(r,'html.parser')
  File "C:\Users\skull\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Models_Resource_Importer\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
Models_Resource_Importer.bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html.parser. Do you need to install a parser library?`

**Comment by furry72** [comment]
and same

**Comment by Grumpykitten03** [comment]
I'm still having this issue
